#### catch([rejectCallback])
`promise.then(null, rejectCallback)`と同義。

##### Parameters
* rejectCallback(optional) - {any} promise が棄却された時に実行される関数（関数以外なら無視）

##### Returns
* {promise} - rejectCallback の戻り値で履行される新しい promise

##### Example
```js
var value1 = 'value1';
var value2 = 'value2';

var promise1 = new Promise(function (resolver) {
  setTimeout(function () {
    resolver.reject(value1);
  }, 100);
});

var promise2 = promise1.catch(function (arg) {
  console.log(arg === value1);
  return value2;
});

promise2.then(function (arg) {
  console.log(arg === value2);
});
```
